### ISSUE TITLE
script configuracion

### ISSUE THREAD

**Issue by lobolanja** [lobolanja/rt4all#3]

**Comment by pedrotoba** [comment]
**PC**

- [Instalar Node js para que funcione la interfaz (Electron)](https://github.com/lobolanja/rt4all/blob/master/_doc/setup_electron.md)
- [Paquetes necesarios para la retransmision de video](https://github.com/lobolanja/rt4all/blob/master/_doc/setup_gstreamer.md)

**Robot**
- Preparar imagen a instalar (rti, gstreamer, raspivid)
- Arrancar scripts automaticamente, (readers, writers, servidor socket)

**Comment by LuciaAlvarez** [comment]
Python

>pip install matplotlib
>pip install reportlab
>pip install numpy
